### PR TITLE
Make ETag visible on response

### PR DESCRIPTION
**Pull request by leoafarias**
This gives the ability to add custom logic around long term caching on an app.

### CODE REVIEW

**Comment by Topener** [comment]
Thanks! Though I guess the more correct way of implementing this is to return all response headers instead of just one. Will look into it just now

**Comment by leoafarias** [comment]
Great, it seems that we can request all response headers in iOS, but on android that call does not work. So it you will have to call each header individually.

**Comment by Topener** [comment]
Found a solution, will add this to the lib:

```
 if (xhr.getResponseHeaders){ // iOS headers
        result.headers = xhr.getResponseHeaders();
    } else if (xhr.getAllResponseHeaders){ // Android or WindowsPhone headers
        var headers = xhr.getAllResponseHeaders().split("\n");
        result.headers = {};
        for (var i = 0; i < headers.length; i++) {
            var split = headers[i].split(":",2);
            result.headers[split[0]] = split[1];
        };
    }
```

Can you test if this one works for you on both platforms (it does for me)

**Comment by Topener** [comment]
I'm going to close this PR and work on a better implementation in the very near future!

**Pull request closed without merging**
